# Generated by Django 3.1.7 on 2021-04-09 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_id', models.IntegerField(null=True)),
                ('rfid_location', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_id', models.IntegerField(null=True)),
                ('subscriber_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField(null=True)),
                ('asset_name', models.CharField(max_length=200, null=True)),
                ('asset_status', models.CharField(choices=[('Available', 'Available'), ('Taken', 'Taken')], max_length=200, null=True)),
                ('rfid_id', models.ManyToManyField(to='assetstracking.RFID')),
                ('subscriber_id', models.ManyToManyField(to='assetstracking.Subscriber')),
            ],
        ),
        migrations.AddField(
            model_name='rfid',
            name='subscriber_id',
            field=models.ManyToManyField(to='assetstracking.Subscriber'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(null=True)),
                ('employee_name', models.CharField(max_length=200, null=True)),
                ('employee_salary', models.FloatField(null=True)),
                ('subscriber_id', models.ManyToManyField(to='assetstracking.Subscriber')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowing_id', models.IntegerField(null=True)),
                ('start_date', models.DateField(auto_now_add=True, null=True)),
                ('end_date', models.DateField(null=True)),
                ('employee_id_scanned', models.IntegerField(default=0, null=True)),
                ('asset_id_scanned', models.IntegerField(default=0, null=True)),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assetstracking.employee')),
                ('subscriber_id', models.ManyToManyField(to='assetstracking.Subscriber')),
                ('tag_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assetstracking.tag')),
            ],
        ),
    ]
